development:
  adapter: postgresql
  database: campuslink_dev
  username: almada
  password: 123456
  host: localhost
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: campuslink_prd
  username: almadaj
  password: juliano1
  host: localhost
  pool: 5
  timeout: 5000
