default: &default
  adapter: postgresql
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: campuslink_dev

test:
  <<: *default
  database: campuslink_test

production:
  <<: *default
  database: campuslink_prd
  username: postgres
  password: <%= ENV['YOUR_PRODUCTION_DATABASE_PASSWORD'] %>